const User = require('../db/model/userModel');
const bcrypt = require('bcrypt')
const sendEmail = require('../utils/send-email').sendEmail
const addEmployeeEmailTemplate = require('../controller/email-templates/addManagerTemplate').addEmployeeEmailTemplate

exports.addManager = async (req, res) => {
    try {
        const { name, email, phone } = req.body;

        // Only admin can add manager
        if (req.user.role !== 'admin') {
            return res.status(403).json({ message: 'Forbidden: You are not an admin' });
        }

        // Validate fields
        if (!name || !email || !phone) {
            return res.status(400).json({ message: 'Name, email & phone are required' });
        }

        // Check if manager already exists
        const existingManager = await User.findOne({ email });
        if (existingManager) {
            return res.status(400).json({ message: 'Manager already exists' });
        }

        // ⭐ AUTO-GENERATE PASSWORD
        const autoGeneratedPassword = Math.random().toString(36).slice(-8); // 8-char random password

        // Hash password
        const hashedPassword = await bcrypt.hash(autoGeneratedPassword, 10);

        // Create new manager
        const newManager = new User({
            name,
            email,
            password: hashedPassword,
            phone,
            role: 'manager',
            isFirstLogin: true
        });

        // Save manager in DB
        await newManager.save();
        
        // Prepare email content
        const emailTemplate = await addEmployeeEmailTemplate(
            name,
            email,
            { role: "manager" },
            autoGeneratedPassword   // Send generated password
        );

        // Send email
        await sendEmail(email, "Your Manager Account Login Credentials", emailTemplate);


        res.status(201).json({
            message: "Manager added successfully",
            manager: newManager
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: "Internal Server Error" });
    }
};
